name: Generate documentation with Antora

on:
  workflow_call:
    inputs:
      path:
        type: string
        required: false
        default: './'
      playbook:
        type: string
        required: false
        default: 'local-antora-playbook.yml'
      publish:
        type: boolean
        required: false
        default: false
      run-scheduled-in-forks:
        type: boolean
        required: false
        default: false

jobs:
  docs:
    name: Antora
    if: >-
      github.event.repository.fork == false || 
      github.event_name != 'schedule' || 
      (github.event_name == 'schedule' && github.event.repository.fork == true && inputs.run-scheduled-in-forks == true)
    runs-on: ubuntu-20.04
    steps:
      - name: Block deprecated repos in /etc/hosts
        run: |
          sudo echo "127.0.0.1 repo.scala-sbt.org" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 repo.typesafe.com" | sudo tee -a /etc/hosts
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-antora@3.1.5-lunr-extension@1.0.0-alpha.8-tabs@1.0.0-beta.6
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Antora and extensions
        run: >-
          npm i -D -E --quiet --no-progress 
          @antora/cli@3.1.5 
          @antora/site-generator@3.1.5 
          @antora/lunr-extension@1.0.0-alpha.8 
          @asciidoctor/tabs@1.0.0-beta.6
        working-directory: ${{ inputs.path }}

      - name: Build documentation
        run: npx antora ${{ inputs.playbook }}
        working-directory: ${{ inputs.path }}

      - name: Publish to GitHub Pages
        if: ${{ inputs.publish && github.event.repository.fork == false }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ inputs.path }}/build/site
          force_orphan: true
          commit_message: "Deploy docs"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
