name: Command with a default JVM, coursier caching and an optional matrix

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        default: ''
      java:
        type: string
        required: false
        default: "11"
      java-index:
        type: string
        required: false
        default: ''
      scala:
        type: string
        required: false
        default: ""
      add-dimensions:
        type: string
        required: false
        default: "{}"
      include:
        type: string
        required: false
        default: "[]"
      exclude:
        type: string
        required: false
        default: "[]"
      cmd:
        type: string
        required: true
      env:
        type: string
        required: false
        default: ""
      cache-key:
        type: string
        required: false
        default: ""
      cache-path:
        type: string
        required: false
        default: ""
      ignore-job-coursier-cache:
        type: boolean
        required: false
        default: true
      ignore-matrix-coursier-cache:
        type: boolean
        required: false
        default: true
      extra-coursier-cache-key:
        type: string
        required: false
        default: ''
      run-scheduled-in-forks:
        type: boolean
        required: false
        default: false
      gradle-build-root:
        type: string
        required: false
        default: ""

jobs:
  prepare-matrix:
    name: Prepare Matrix
    if: >-
      github.event.repository.fork == false || 
      github.event_name != 'schedule' || 
      (github.event_name == 'schedule' && github.event.repository.fork == true && inputs.run-scheduled-in-forks == true)
    runs-on: ubuntu-20.04
    outputs:
      matrix: ${{ steps.prepare-matrix.outputs.matrix }}
    steps:
    - id: prepare-matrix
      run: |
        add_dimensions=$(echo -n '${{ inputs.add-dimensions }}' | sed 's/^.*{//;s/}.*$//') # Remove leading { and trailing }
        # input java/scala | replace whitespaces/commas/quotes by newline | drop empty | quotation | join by comma
        java=$(echo -n '${{inputs.java}}' | sed 's/[[:blank:],"]\+/\n/g' | awk NF | sed 's/^..*$/"&"/' | sed ':a; N; $!ba; s/\n/,/g')
        scala=$(echo -n '${{inputs.scala}}' | sed 's/[[:blank:],"]\+/\n/g' | awk NF | sed 's/^..*$/"&"/' | sed ':a; N; $!ba; s/\n/,/g')
        matrix="{"
        matrix+="\"java\": [$java],"
        [[ ! -z "$scala" ]] && matrix+="\"scala\": [$scala],"
        matrix+="$(echo ${add_dimensions:+$add_dimensions,})"
        matrix+="\"include\":$(echo -n '${{ inputs.include }}'),"
        matrix+="\"exclude\":$(echo -n '${{ inputs.exclude }}')"
        matrix+="}"
        # Cleanup JSON (no unnecessary whitespaces, etc.)
        matrix=$(jq -n -c "$matrix")
        echo $matrix
        echo "matrix=$matrix" >> $GITHUB_OUTPUT
  cmd:
    name: ${{ toJSON(matrix) }}
    if: ${{ github.event.repository.fork == false || github.event_name != 'schedule' || (github.event_name == 'schedule' && github.event.repository.fork == true && inputs.run-scheduled-in-forks == true) }}
    needs: prepare-matrix
    runs-on: ubuntu-20.04
    strategy:
      # WA: https://github.community/t/reusable-workflow-with-strategy-matrix/205676/6
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - name: Block deprecated repos in /etc/hosts
        run: |
          sudo echo "127.0.0.1 repo.scala-sbt.org" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 repo.typesafe.com" | sudo tee -a /etc/hosts
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Set ENV variables
        if: inputs.env != ''
        run: echo '${{ inputs.env }}' >> $GITHUB_ENV

      - name: Coursier Cache
        id: coursier-cache
        uses: coursier/cache-action@v6
        with:
          ignoreJob: ${{ inputs.ignore-job-coursier-cache }}
          ignoreMatrix: ${{ inputs.ignore-matrix-coursier-cache }}
          extraKey: ${{ inputs.extra-coursier-cache-key }}

      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v1
        with:
          build-root-directory: ${{ inputs.gradle-build-root }}
          # Disable caching of ~/.gradle/caches/build-cache-*
          save-local-build-cache: false
          # Disable caching of ~/.m2/repository/
          save-maven-dependencies-cache: false

      - name: Custom Cache
        uses: actions/cache@v3
        if: ${{ inputs.cache-key != '' && inputs.cache-path != '' }}
        with:
          key: ${{ format(inputs.cache-key, matrix.java) }}
          path: ${{ inputs.cache-path }}

      - name: Install Adoptium Temurin OpenJDK
        uses: coursier/setup-action@v1
        with:
          jvm: adoptium:${{ matrix.java }}
          jvm-index: ${{ inputs.java-index }}

      - name: Print helpful configs and files and show environment
        run: |
          echo "Matrix: ${{ toJSON(matrix) }}"
          echo "$ cat /etc/sbt/jvmopts"
          cat /etc/sbt/jvmopts || true
          echo ""
          echo "$ cat /etc/sbt/sbtopts"
          cat /etc/sbt/sbtopts || true
          echo ""
          echo "$ env"
          env
          echo "ls -alFhR ~/.ivy2 | grep play | grep jar"
          ls -alFhR ~/.ivy2 | grep play | grep jar || true
          echo "ls -alFhR ~/.cache/coursier | grep play | grep jar"
          ls -alFhR ~/.cache/coursier | grep play | grep jar || true

      - name: Convert matrix elements to environment variables
        run: |
          jq -n -r '$in | to_entries|map("MATRIX_\(.key|ascii_upcase)=\(.value|tostring)")|.[]' --argjson in '${{ toJSON(matrix) }}' >> $GITHUB_ENV

      - name: Run command
        run: ${{ inputs.cmd }}
        env:
          CACHE_HIT_COURSIER: ${{ steps.coursier-cache.outputs.cache-hit-coursier }}

      - name: Cleanup before cache
        shell: bash
        run: |
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
