name: Command with a default JVM, coursier caching and an optional matrix

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false
        default: ''
      java:
        type: string
        required: false
        default: "17"
      java-index:
        type: string
        required: false
        default: ''
      cmd:
        type: string
        required: true
      env:
        type: string
        required: false
        default: ""
      cache-key:
        type: string
        required: false
        default: ""
      cache-path:
        type: string
        required: false
        default: ""
      ignore-job-coursier-cache:
        type: boolean
        required: false
        default: true
      ignore-matrix-coursier-cache:
        type: boolean
        required: false
        default: true
      extra-coursier-cache-key:
        type: string
        required: false
        default: ''
      run-scheduled-in-forks:
        type: boolean
        required: false
        default: false
      gradle-build-root:
        type: string
        required: false
        default: ""
      gradle-cache-read-only:
        type: boolean
        required: false
        default: false

jobs:
  cmd:
    if: ${{ github.event.repository.fork == false || github.event_name != 'schedule' || (github.event_name == 'schedule' && github.event.repository.fork == true && inputs.run-scheduled-in-forks == true) }}
    runs-on: ubuntu-24.04
    steps:
      - name: Block deprecated repos in /etc/hosts
        run: |
          sudo echo "127.0.0.1 repo.scala-sbt.org" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 repo.typesafe.com" | sudo tee -a /etc/hosts
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Set ENV variables
        if: inputs.env != ''
        run: echo '${{ inputs.env }}' >> $GITHUB_ENV

      - name: Coursier Cache
        id: coursier-cache
        uses: coursier/cache-action@v7
        with:
          ignoreJob: ${{ inputs.ignore-job-coursier-cache }}
          ignoreMatrix: ${{ inputs.ignore-matrix-coursier-cache }}
          extraKey: ${{ inputs.extra-coursier-cache-key }}

      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v3
        if: ${{ hashFiles(format('{0}{1}{2}', inputs.gradle-build-root, inputs.gradle-build-root && '/' || '', 'gradle/wrapper/gradle-wrapper.properties')) != '' }}
        with:
          build-root-directory: ${{ inputs.gradle-build-root }}
          # Disable caching of ~/.gradle/caches/build-cache-*
          save-local-build-cache: false
          # Disable caching of ~/.m2/repository/
          save-maven-dependencies-cache: false
          read-only: ${{ inputs.gradle-cache-read-only }}

      - name: Custom Cache
        uses: actions/cache@v4
        if: ${{ inputs.cache-key != '' && inputs.cache-path != '' }}
        with:
          key: ${{ format(inputs.cache-key, inputs.java) }}
          path: ${{ inputs.cache-path }}

      - name: Install Adoptium Temurin OpenJDK
        uses: coursier/setup-action@v1
        with:
          jvm: adoptium:${{ inputs.java }}
          jvm-index: ${{ inputs.java-index }}

      - name: Install sbt
        uses: sbt/setup-sbt@v1

      - name: Print helpful configs and files and show environment
        run: |
          echo "$ cat /etc/sbt/jvmopts"
          cat /etc/sbt/jvmopts || true
          echo ""
          echo "$ cat /etc/sbt/sbtopts"
          cat /etc/sbt/sbtopts || true
          echo ""
          echo "$ env"
          env
          echo "ls -alFhR ~/.ivy2 | grep play | grep jar"
          ls -alFhR ~/.ivy2 | grep play | grep jar || true
          echo "ls -alFhR ~/.cache/coursier | grep play | grep jar"
          ls -alFhR ~/.cache/coursier | grep play | grep jar || true

      - name: Run command
        run: ${{ inputs.cmd }}
        env:
          CACHE_HIT_COURSIER: ${{ steps.coursier-cache.outputs.cache-hit-coursier }}

      - name: Cleanup before cache
        shell: bash
        run: |
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
