name: Mark Pull Request as Ready To Merge

on:
  workflow_call:

jobs:
  cmd:
    name: Ready To Merge
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - name: Ready To Merge
        run: echo 'Ready To Merge'
